version: '3'
services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - flask
  consumer:
    build: ./consumer
    depends_on:
      - app
    networks:
      - flask
networks:
  flask:
    driver: bridge